const data =[
    {
        id:1,
        img:'/image/tourlist/book-list-1.jpg',
        h6:123,
        h1:'Luxory Small Comet',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Yacht',
        guests:'9 guests',
        cabins:'6 cabins',
        km:'80km',
    },
    {
        id:2,
        img:'/image/tourlist/book-list-2.jpg',
        h6:114,
        h1:'Odyssey Yacht',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Yacht',
        guests:'6 guests',
        cabins:'4 cabins',
        km:'90km',
    },
    {
        id:3,
        img:'/image/tourlist/book-list-3.jpg',
        h6:164,
        h1:'Bawera Cruiser ',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Cruiser',
        guests:'46 guests',
        cabins:'26 cabins',
        km:'90km',
    },
    {
        id:4,
        img:'/image/tourlist/book-list-4.jpg',
        h6:144,
        h1:'Cross Ocean Yacht ',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Yacht',
        guests:'32 guests',
        cabins:'16 cabins',
        km:'100km',
    },
    {
        id:5,
        img:'/image/tourlist/book-list-5.jpg',
        h6:114,
        h1:'Campe Cruiser ',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Cruiser',
        guests:'10 guests',
        cabins:'6 cabins',
        km:'90km',
    },
    {
        id:6,
        img:'/image/tourlist/book-list-6.jpg',
        h6:123,
        h1:'Comet Yacht',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Yacht',
        guests:'9 guests',
        cabins:'6 cabins',
        km:'80km',
    },
    {
        id:7,
        img:'/image/tourlist/book-list-6.jpg',
        h6:125,
        h1:'Aariel Yacht ',
        p:'Lorem ipsum dolor sit amet, consectetuer adipiscing elit nean commodo ligula eget dolor. Aenean massa cum sociis Theme natoque magnis et penatibus dis. Sed consequat, leo eget bibendum sodales, augue',
        type:'Yacht',
        guests:'9 guests',
        cabins:'6 cabins',
        km:'80km',
    },
]
export default data