const products=[
    {
        id:1,
        img:'/image/products/1.jpg',
        name:'Grey Rope',
        price:2860,
        category:'Luxory',
        rating:4,
    },
    {
        id:2,
        img:'/image/products/2.jpg',
        name:'Bussola',
        price:580,
        category:'Grand Marina',
        rating:5,
    },
    {
        id:3,
        img:'/image/products/3.jpg',
        name:'Attention To Details',
        price:5280,
        category:'The Caribbean',
        rating:3,
    },
    {
        id:4,
        img:'/image/products/4.jpg',
        name:'Mini Compass',
        price:3200,
        category:'Luxory',
        rating:4,
    },
    {
        id:5,
        img:'/image/products/5.jpg',
        name:'Boat Flooring',
        price:4330,
        category:'Grand Marina',
        rating:5,
    },
    {
        id:6,
        img:'/image/products/6.jpg',
        name:'Binoculars',
        price:4350,
        category:'Details',
        rating:3,
    },
    {
        id:7,
        img:'/image/products/7.jpg',
        name:'Outboard Motors',
        price:3698,
        category:'Details',
        rating:4,
    },
    {
        id:8,
        img:'/image/products/8.jpg',
        name:'Boat Compass',
        price:3254,
        category:'Grand Marina',
        rating:4,
    },
    {
        id:9,
        img:'/image/products/9.jpg',
        name:'Fishing Chair',
        price:1254,
        category:'Superyachts',
        rating:3,
    },
    {
        id:10,
        img:'/image/products/10.jpg',
        name:'Field Glasses',
        price:4652,
        category:'Details',
        rating:5,
    },
    {
        id:11,
        img:'/image/products/3.jpg',
        name:'Sea Range',
        price:3216,
        category:'Sailing Cruise',
        rating:4,
    },
    {
        id:12,
        img:'/image/products/4.jpg',
        name:'Sea Fishing',
        price:6231,
        category:'Superyachts',
        rating:3,
    },
    {
        id:13,
        img:'/image/products/6.jpg',
        name:'Elegant Yachts',
        price:5624,
        category:'Details',
        rating:5,
    },
    {
        id:14,
        img:'/image/products/8.jpg',
        name:'Boat Engine',
        price:3462,
        category:'Sailing Cruise',
        rating:4,
    },
    {
        id:15,
        img:'/image/products/2.jpg',
        name:'Yacht Details',
        price:4252,
        category:'Superyachts',
        rating:3,
    },
]
export default products